### ISSUE TITLE
Tab Navigation does not work on Safari

### ISSUE THREAD

**Issue by yangwong9664** [hmrc/platui-support#2]
## Description of the issue

When pressing Tab on a service that supports tab navigation, a yellow bar should appear at the top that says "Skip to main content", when clicking the link in the bar, it should scroll to the main content on the page.

This feature works on all browsers except Safari on Mac, we would like to know if there is a design pattern that enables this to work on Mac by default.

## Steps to reproduce the issue

One service I know of that uses this is called ATAR (Advanced tariff rulings, operational service).
[Link here](https://confluence.tools.tax.service.gov.uk/x/LYoJBg)
Scroll to ATAR Operational service section, and use QA or Staging URL, use any string for PID and paste one valid role to login. When on the service, pressing tab should activate this feature. It doesn't work for Mac however. 

## Actual vs expected behaviour

Pressing tab on a page that supports the skip to main content button, should make a yellow bar appear at the top, with a link that says "skip to main content", then the page moves to the main content, the bar does not appear by default on a Mac on Safari.

## Environment (where applicable)

- Operating system: iOS
- Browser: Safari
- Browser version: Any
- Library Name & Version: Any

**Comment by oscarduignan** [comment]
This might be an issue for us to feedback to govuk design system team, because opening https://design-system.service.gov.uk/components/skip-link/default/index.html with safari I can't access the skip link there either. Maybe I'm forgetting something basic though, will see if we can ask a few more people to take a look first

![CleanShot 2022-01-05 at 11 26 14](https://user-images.githubusercontent.com/100650/148210421-ca3c0b36-e90f-486c-bc98-615ab63c2296.gif)

MacOS Big Sur 11.5.2 (20G95)
Safari Version 14.1.2 (16611.3.10.1.6)

**Comment by kyle-bowden** [comment]
Hi @yangwong9664 

I tested on a Mac using Browserstack.com with a Mac(Monterey) and Safari(15.1), it worked for me when i tabbed to main content and then pressed enter.

**Comment by oscarduignan** [comment]
@yangwong9664 apologies, this is a quirk of safari, where tab navigation of web pages has to be turned on in safari's preferences to work. I had an inkling there was something like this that I'd forgotten about, here's an example:

![CleanShot 2022-01-05 at 13 44 04](https://user-images.githubusercontent.com/100650/148227493-b8fc13d3-3cf6-44ad-b8ab-9bee3aa20312.gif)
