### ISSUE TITLE
InternalHeader to include NavigationLinks

### ISSUE THREAD

**Issue by frobian21** [hmrc/platui-support#5]
## Related component
[InternalHeader](https://design.tax.service.gov.uk/hmrc-design-patterns/internal-header/)

## Context
We would like to use navigation items with an InternalHeader like the ones that are available for [Header](https://design.tax.service.gov.uk/hmrc-design-patterns/header/), which is currently not available.

## Alternatives
Currently, we've manually adjusted the HTML instead of using the InternalHeader component, we had to add the data module so that the javascript was pulled in.

## Additional information (if applicable)
None,  it's an internal component so we didn't do accessibility testing - Besides, I imagine the Navigation Links have already been tested with the standard Header

**Comment by oscarduignan** [comment]
HI @frobian21 thank you for sharing this, we're going to raise the possibility of changing the internalHeader component API with the design resources team, and when we have a ticket to track any work related I'll share it with you directly 👍 

In terms of accessibility testing, I'm not familiar enough with the specifics of how the navigation links are coded to say for sure that use as they are within the internal header would not cause any accessibility issues, so I would always advise retesting. With accessibility it's also especially important to understand that the accessibility of a use of a component is context dependant, so an accessible pattern could be used in an inaccessible way, depending on the context.

I think the data-module bit you had to adjust is a long standing (but unknown to us) bug that we should soon have fixed with the hmrcHeader component https://github.com/hmrc/hmrc-frontend/pull/207

**Comment by oscarduignan** [comment]
Hi @frobian21 we were able to raise this with the design resources working group last week. The consensus was that rather than adding menu items to the internal header, they would suggest using a pattern like the Personal Tax Account (PTA) Account Menu component ([HmrcAccountMenu](https://github.com/hmrc/hmrc-frontend/blob/main/src/components/account-menu/template.njk)). Which isn't provided as a generic component at the moment, it's PTA specific, but it seems like based on the demand for a generic version of something like this, that providing one is probably on the future roadmap for design resources. To follow any progress on that / contribute to the design you can comment in and subscribe to the [design pattern issue thread for the account header pattern](https://github.com/hmrc/design-patterns/issues/128)

![CleanShot 2022-02-22 at 07 53 38@2x](https://user-images.githubusercontent.com/100650/155086999-971cf2a2-4b0f-4e78-ac24-5c506c01485d.png)
