### ISSUE TITLE
GovukDetails to support adding attributes on nested <span>

### ISSUE THREAD

**Issue by tipperba** [hmrc/platui-support#7]
## Related component
GovukDetails

## Context
We have a performance analytics requirement to add a "data-linktext" attribute on the `span` nested within the `summary` child of the `details` element. This will allow our analytics to track more precisely which elements are clicked. Currently GovukDetails allows you to add attributes to the top-level `details`, but not to the `summary` or the `span` within the `summary`. 

We originally added the attribute to `details`, but Google Tag Manager (GTM) cannot read it as the user actually clicks on the `span` within and GTM can only read the attribute from the clicked-on element, not the ancestor element. 

## Alternatives
To roll our own `details` component, which we would rather avoid.

**Comment by oscarduignan** [comment]
Hi @tipperba, I think this might be the same issue that @DanielConnelly has raised with us in #8, I've put a [comment there asking if Daniel can share some more information to help us understand the problem better](https://github.com/hmrc/platui-support/issues/8#issuecomment-1029850078). If you're on a different team or also have any context that we could use would you also be able to forward it to [platform-ui@digital.hmrc.gov.uk](mailto:platform-ui@digital.hmrc.gov.uk)

I should be able to raise this for further discussion with our PO at some point next week

**Comment by DanielConnelly** [comment]
@oscarduignan I would disagree on this, as my issue (https://github.com/hmrc/platui-support/issues/8) is about raising attributes onto elements that do not have attributes currently, while this specifically attributes on a details object, being applied to the top-level details element and not applicable to an internal element, e.g the top-level summary text.


I suggest this issue, is different as the details object should have customizability for the top whole object, the summary element and the contents element.  Ideally 

@govukDetails(Details(
    summary = Summary(content = Text(messages(summary)), attributes = Map()),
    content = DetailsContent(content = content, attributes = Map()),
    attributes = Map("data-linktext" -> messages.english(summary))
))

**Comment by HollyHughes** [comment]
Hi @tipperba,

I just thought I would reach out as I realise it's been a couple of weeks since you initially raised this query and @oscarduignan came back to you. 

Reading through the chain above, please could you (or someone from your team) share a bit more information with us via this email address platform-ui@digital.hmrc.gov.uk that would be an enormous help. This could be any documentation, other tickets that may be linked to this work just to help us understand the core issue a little more. From there we can iron out any outstanding questions, agree any next steps and I can look at prioritisation (if this is something we agree to do) 😊
