### ISSUE TITLE
Attributes field to be Added to all components to allow extendability 

### ISSUE THREAD

**Issue by DanielConnelly** [hmrc/platui-support#8]
## Related component
Details Link, Get Help With this Page, Language Select, NewTabLink and any other link like components

## Context

We have a requirement from our Performance Analyst to provide English content on all links, even when the language is switched to welsh. To meet this, we would like the ability to add attributes (specifically a "data-linktext" attribute) to the components listed above. 

## Alternatives

We cannot work around it without re-writing all the above components.

## Additional information (if applicable)

We have a requirement from the business to better track across 11 + languages and as our service RORO is large the maintenance cost alone to ensure each link is tracked properly in GA would be time-consuming.

**Comment by oscarduignan** [comment]
Hi @DanielConnelly thanks for raising this, we need to consider API changes quite a lot before we implement them because they can have a big impact cumulatively across the platform

To rephrase the problem a bit to check my understanding, at the moment the analytics code isn't able to identify that links are the same if they have different translations, and your performance analyst has suggested adding the english translation to links as a data attribute to provide a means of correlating events involving these links

I can imagine for this we might want to reach out to your performance analyst to try and better understand what their needs are here, would you be able to share some contact information and links to related tickets at platform-ui@digital.hmrc.gov.uk so that I can request the time to do some follow up on this from our product owner

**Comment by HollyHughes** [comment]
Hi @DanielConnelly 

Just checking over the open issues and I realise it's been a couple of weeks since you initially raised this query and @oscarduignan came back to you.

Reading through the initial ask, I can understand what you're asking for, however, given the potential complexity of API changes, I would be a bit reserved about launching into making any changes without a more in depth understanding of the core problem that you're trying to fix. 

Given the current architecture of our libraries, some of the solutions are more difficult to implement than others; once we have a greater understanding of the core issue at hand, we will be able to look into the best solution for your team. If either yourself or someone from your team could share a bit more information with us (or any other tickets that may be linked to this work) via this email address platform-ui@digital.hmrc.gov.uk that would be an enormous help. From there we can agree any next steps and I will be able to prioritise the work (if it is something we agree to do!) 😊
